import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Link from "next/link";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const pops = Poppins({ weight: "200", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={pops.className}>{children}</body>
      </UserProvider>
    </html>
  );
}
