import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import Link from "next/link";
import Head from "next/head";
import { NavBar } from "./components/navigation/desktop/nav-bar";

const inter = Inter({ subsets: ["latin"] });
const pops = Poppins({ weight: "200", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">

        <body className="w-[--template-max-width] mx-auto font-poppins">

          <NavBar />
          {children}

        </body>
      
    </html>
  );
}
